### ISSUE TITLE
HiFi-GAN声码器的激活函数(?)选择

### ISSUE THREAD

**Issue by yzmyyff** [alibaba-damo-academy/KAN-TTS#19]
你好,

我注意到我们的HiFi-GAN在upsample部分, 会先进行一个

```python
x = torch.sin(x) + x
```

这里似乎是替换了原始实现中的激活函数, 请问这个有参考文献吗?  还是实验结果验证?

**Comment by hukai-sun** [comment]
> 你好,
> 
> 我注意到我们的HiFi-GAN在upsample部分, 会先进行一个
> 
> ```python
> x = torch.sin(x) + x
> ```
> 
> 这里似乎是替换了原始实现中的激活函数, 请问这个有参考文献吗? 还是实验结果验证?

here, TFGAN: TIME AND FREQUENCY DOMAIN BASED GENERATIVE ADVERSARIAL NETWORK FOR HIGH-FIDELITY SPEECH SYNTHESIS (https://arxiv.org/abs/2011.12206)

**Comment by yzmyyff** [comment]
Thanks a lot for your reply. 

FYI, the sine activation is a simplified variant of snake (https://arxiv.org/pdf/2206.13404.pdf).
And Nvidia BigVGAN also uses it.
Did we try that?

**Comment by hukai-sun** [comment]
> Thanks a lot for your reply.
> 
> FYI, the sine activation is a simplified variant of snake (https://arxiv.org/pdf/2206.13404.pdf). And Nvidia BigVGAN also uses it. Did we try that?

yeah, you are right. both the sine and the snake  provide a periodicity inductive bias to the generator.
