### ISSUE TITLE
墨大社区显示语音功能只能跑tensorflow1.15环境，而KAN-TTS用的是pytorch

### ISSUE THREAD

**Issue by jinfagang** [alibaba-damo-academy/KAN-TTS#24]
这是为何？有什么办法用KANTTS load 墨大社区的权重进行本地预测吗？
然后进行ONNX导出？

**Comment by GinChow** [comment]
Hi @jinfagang, did you mean [魔搭社区](https://modelscope.cn/models?page=1&tasks=text-to-speech)？ Thanks for your interest in the models we released, actually some of them are in the beta version which is a mixture of TF and pytorch, we will update pure-pytorch models recently. For now, you can have a try on these two models  https://modelscope.cn/models/speech_tts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k/summary , https://modelscope.cn/models/speech_tts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_24k/summary,  they are both supported by KAN-TTS :)

**Comment by jinfagang** [comment]
@GinChow thank u for your reply. I wanna using the raw pth weights and load using KANTTS rather than using modelscope, Are there any instructions to do so?

**Comment by GinChow** [comment]
Just clone the pre-trained models via git
```bash
# 16k model
git clone -b pretrain http://www.modelscope.cn/speech_tts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k.git
# 24k model
git clone -b pretrain http://www.modelscope.cn/speech_tts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_24k.git
```
then follow this tutorial https://github.com/alibaba-damo-academy/KAN-TTS/wiki/text_to_wav_manual

**Comment by GinChow** [comment]
Hi @jinfagang , all of the TTS models on ModelScope are now in PyTorch format. You can simply clone the repository and load the models using KAN-TTS.
