### ISSUE TITLE
使用通用格式数据微调Sambert-hifigan出现报错

### ISSUE THREAD

**Issue by wjddd** [alibaba-damo-academy/KAN-TTS#26]
微调步骤参考：https://mp.weixin.qq.com/s/Xo-pMe3-P-fJ-32Z1JLonA
已尝试过：
kantts/configs/sambert_16k_MAS.yaml（发音人已修改）
speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k/basemodel_16k/sambert/config.yaml（发音人已修改）

通用数据格式如下：

```
.
├── prosody
│   └── prosody.txt
└── wav
    ├── 1.wav
    ├── 2.wav
    ├── ...
    └── 9000.wav
```

报错信息如下：
```
Traceback (most recent call last):
  File "kantts/bin/train_sambert.py", line 231, in <module>
    args.local_rank,
  File "kantts/bin/train_sambert.py", line 122, in train
    pin_memory=config["pin_memory"],
  File "/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

```

**Comment by GinChow** [comment]
Hi @wjddd, did you finetune with the [AISHELL3](https://www.modelscope.cn/datasets/speech_tts/AISHELL-3/summary) dataset? If so, on which speaker you ran into this issue? If not, what is your dataset like?

**Comment by wjddd** [comment]
> Hi @wjddd, did you finetune with the [AISHELL3](https://www.modelscope.cn/datasets/speech_tts/AISHELL-3/summary) dataset? If so, on which speaker you ran into this issue? If not, what is your dataset like?

SSB0011 from AISHELL3, and interval directory deleted

**Comment by wjddd** [comment]
Hi @GinChow , is there any solution?

**Comment by wjddd** [comment]
> For now, the released pre-trained sambert model is limited to fine-tuning datasets which contain intervals. Fine-tuning on general data relies on pre-trained sambert-MAS model which will be released in the future, please look forward to it.

So many thanks for your job!! BTW, is there any tool to help us generate or annotate the intervals?

**Comment by GinChow** [comment]
If you are going to do it yourself, https://www.fon.hum.uva.nl/praat/  is what you need, but I think it will take you tons of time.

**Comment by xiaozhi2015** [comment]
Is there any open source tools to generate intervals in your format, such as mfa? @GinChow

**Comment by xiaozhi2015** [comment]
Mfa can generate similar mit-style intervals data, but the phones of them are not exactly the same.
Have you fine-tuned a sambert-hifigan model on general data successfully? @wjddd
