### ISSUE TITLE
请问ttsfrd包是怎么下的？

### ISSUE THREAD

**Issue by 15755841658** [alibaba-damo-academy/KAN-TTS#29]
无论是直接pip install ttsfrd，还是使用清华、豆瓣、阿里云镜像都会出现
ERROR: Could not find a version that satisfies the requirement ttsfrd (from versions: none)
ERROR: No matching distribution found for ttsfrd

**Comment by GinChow** [comment]
We recommend you guys configure the virtual environment via anaconda.
```bash
conda env create -f environment.yaml
```
`ttsfrd` is included in the yaml config file.
```yaml
# environment.yaml
    - --find-links https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
    - ttsfrd
```
Or if you want to install this package individually, try this command
```bash
pip install ttsfrd -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
```

**Comment by 15755841658** [comment]
@GinChow 
非常感谢您的回复，我使用“魔塔”发布的预训练模型合成出的语音，每句话的开始会出现一点点吞音的情况，是哪里的参数需要修改吗？每句话最开始几乎没有静音段。

**Comment by 15755841658** [comment]
@GinChow 
非常感谢您的回复，我使用“魔塔”发布的预训练模型合成出的语音，每句话的开始会出现一点点吞音的情况，是哪里的参数需要修改吗？每句话最开始几乎没有静音段。

**Comment by GinChow** [comment]
> 

Could you show me the case? A spectrogram or waveform plot is okay.

**Comment by 15755841658** [comment]
@GinChow 
![image](https://user-images.githubusercontent.com/45281733/209048966-ea1fbaa6-61aa-4149-a98c-89673e57fad2.png)
![image](https://user-images.githubusercontent.com/45281733/209049044-c8200acf-7017-4992-97f1-1e383543d1e2.png)

**Comment by 15755841658** [comment]
@GinChow 
我使用的是“魔塔社区”开源的的预训练模型直接来进行合成语音，所有合成音都是这样的，开头和结尾几乎没有什么静音段，开头会有一点点的吞音(很少，但是能听出来)

**Comment by GinChow** [comment]
> 



> @GinChow ![image](https://user-images.githubusercontent.com/45281733/209048966-ea1fbaa6-61aa-4149-a98c-89673e57fad2.png) ![image](https://user-images.githubusercontent.com/45281733/209049044-c8200acf-7017-4992-97f1-1e383543d1e2.png)

From the spectrogram, I can't tell any truncated area among the leading wave. I think it could be an issue of the device playing latency, please try to paste a silence before the leading wave.

**Comment by 15755841658** [comment]
@GinChow 
嗯嗯，那开始和结束静音段也几乎没有，这个是有参数调整，还是自己添加一段静音段在开始和结束

**Comment by GinChow** [comment]
> 

You can do it yourself.

**Comment by SaltedSlark** [comment]
hi when I try to download ttsfrd, I got error like this:
![image](https://github.com/alibaba-damo-academy/KAN-TTS/assets/32287808/4dd4070f-0c55-4cd8-b568-796a877e4678)
