### ISSUE TITLE
数据集中的#符号是什么意思？

### ISSUE THREAD

**Issue by 503718696** [alibaba-damo-academy/KAN-TTS#33]
数据集中的#符号是什么意思？#1，#2，#3，#4
002853	法律#2只是#1傀儡#3、司法#1公正#2只是#1口号#4。
fa3 lv4 zhi3 shi4 kui6 lei3 si1 fa3 gong1 zheng4 zhi3 shi4 kou3 hao4

**Comment by GinChow** [comment]
These boundary tags indicate breaks in the corresponding audio file, with larger numbers meaning longer breaks. In particular, "#4" usually marks the end of a sentence.
