### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Pydataman** [alibaba-damo-academy/KAN-TTS#34]
hello, in kantts_sambert.py code, line 967-975.
 LFR_text_inputs = LR_text_outputs.contiguous().view(batch_size, -1, self.mel_decoder.r * text_hid.shape[-1])
 LFR_emo_inputs = LR_emo_outputs.contiguous().view(batch_size, -1, self.mel_decoder.r * emo_hid.shape[-1])[:, :, : emo_hid.shape[-1]]
LFR_spk_inputs = LR_spk_outputs.contiguous().view(batch_size, -1, self.mel_decoder.r * spk_hid.shape[-1])[:, :, : spk_hid.shape[-1]]

if  data.size() = [64, 100, 40],  r = 3, 
data.contiguous().view(64, -1, 3 * 40) error

**Comment by GinChow** [comment]
Please provide more context of your issue, like dataset, training env, log file, etc.
