### ISSUE TITLE
ttsfrd模块有返回拼音、正则化文本的方法吗？

### ISSUE THREAD

**Issue by kquark** [alibaba-damo-academy/KAN-TTS#35]
大神好，kantts项目有使用到ttsfrd模块来做文本转symbols的逻辑，这个模块很棒！

问下ttsfrd有单独返回拼音、正则化文本的方法吗？如果有的话，怎么使用呢？

**Comment by GinChow** [comment]
For now `ttsfrd` only supports text-symbol converting, those internal functions like TN, POS, disambiguous are not available.
We are considering to opensource `ttsfrd` in the future, please look forward to it :)

**Comment by yygg678** [comment]
> For now `ttsfrd` only supports text-symbol converting, those internal functions like TN, POS, disambiguous are not available. We are considering to opensource `ttsfrd` in the future, please look forward to it :)

你好，ttsfrd 的ttsfrd.cpython-37m-x86_64-linux-gnu.so 库文件，python加载运行时存在内存泄漏，能修复下更新版本吗？

**Comment by ABC0408** [comment]
> > For now `ttsfrd` only supports text-symbol converting, those internal functions like TN, POS, disambiguous are not available. We are considering to opensource `ttsfrd` in the future, please look forward to it :)
> 
> 你好，ttsfrd 的ttsfrd.cpython-37m-x86_64-linux-gnu.so 库文件，python加载运行时存在内存泄漏，能修复下更新版本吗？

升级ttsfrd为0.2.1的版本就不泄露了

**Comment by wukongbuku** [comment]
> For now `ttsfrd` only supports text-symbol converting, those internal functions like TN, POS, disambiguous are not available. We are considering to opensource `ttsfrd` in the future, please look forward to it :)

目前这个问题解决了么，现在这个项目还有人维护吗
