### ISSUE TITLE
sybert怎么应用、有预训练模型吗？

### ISSUE THREAD

**Issue by kquark** [alibaba-damo-academy/KAN-TTS#36]
大神好，这个项目太赞了！不过有一些问题不太明白：

1. 问一下sybert具体怎么使用的，预期达到怎样的效果（训练过程没有音频数据参与，sybert对发音特征建模不太理解）？
在kantts看到有sybert的训练模块，但是没有推理模块，也没有应用的模块。

2. sybert有预训练模型吗？
尝试加载resource目录的languagedata_embedded.bin，但是貌似这不是pytorch模型。

**Comment by hukai-sun** [comment]
hello, 我们的实验初版sybert 在训练数据量较少时可以起到一定的提高发音准确性的作用，但在有基础模型做finetune的情况下，提升有限，可以先不使用。(thus 目前没有提供pretrained model)。我们已经开始在更大的语义建模单元和数据上预训练更适合TTS任务的BERT，预期会整体提高合成语音的韵律，那将会是bert发挥作用更合适的形式，届时会有更新，欢迎关注。
