### ISSUE TITLE
kantts支持多发音人模型吗？

### ISSUE THREAD

**Issue by kquark** [alibaba-damo-academy/KAN-TTS#37]
看kantts的训练指引是单发音人的，即使用aishell3的多发音人的数据训练，也是一个一个训练。
在modelscope开源的多发音人模型，内部是多个声学模型组合的，而不是一个模型。

**问下kantts是否能一个模型支持多个发音人？**
如果不行，具体的原因是什么呢，什么原理导致多发音人会相互干扰？
如果可以，具体怎么操作才可以达到这种效果呢？

**Comment by GinChow** [comment]
Of course, KANTTS supports multi-speaker acoustic model. Those multi-speaker models on [modelscope](https://modelscope.cn/models?page=1&tasks=text-to-speech&type=audio) are all single-AM.

If you want to train a multi-speaker AM, modify `speaker_list` in your config file, then pass multiple `root_dir` in the training command like,
```bash
python kantts/bin/train_sambert.py --model_config YOUR_MODEL_CONFIG  --root_dir OUTPUT_DATA_FEATURE_PATH1 OUTPUT_DATA_FEATURE_PATH2 OUTPUT_DATA_FEATURE_PATH3 ... --stage_dir TRAINING_STAGE_PATH
```
