### ISSUE TITLE
无法多卡训练?

### ISSUE THREAD

**Issue by zjttfs** [alibaba-damo-academy/KAN-TTS#38]
![微信截图_20230117111115](https://user-images.githubusercontent.com/24729880/212801583-00fc7ae5-cfb8-4cc4-aa5a-e1630aba9c1b.png)
```
If your GPU devices are enough, you can use distributed training, which is a lot faster than single GPU training. For example, assign GPU device indexes with CUDA_VISIBLE_DEVICES system variable, --nproc_per_node denotes the count of GPU devices.
```

--nproc_per_node 没有这个参数呀?

**Comment by GinChow** [comment]
`--nproc_per_node` is one of the  PyTorch DDP arguments, https://pytorch.org/docs/stable/distributed.html#launch-utility
